name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Fix permissions for mocha binary
      run: chmod +x ./node_modules/.bin/mocha

    - name: Run tests
      run: npx mocha

    # Fallback: If mocha still fails, install globally and run
    - name: Install mocha globally (fallback)
      if: failure()
      run: npm install -g mocha

    - name: Run tests globally (fallback)
      if: failure()
      run: mocha
